server:
  port: 0

spring:
  application:
    name: notification-service
  rabbitmq:
    password: guest
    username: guest

twilio:
  username: ${TWILIO_USERNAME}
  password: ${TWILIO_PASSWORD}
  phoneNumber: ${TWILIO_PHONENUMBER}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true