server:
  port: 0

spring:
  application:
    name: notification-service
  rabbitmq:
    password: guest
    username: guest
  cloud.stream:
    bindings.input:
      destination: accountNotifications
      group: accountNotificationsGroup

twilio:
  username: ${TWILIO_USERNAME}
  password: ${TWILIO_PASSWORD}
  phoneNumber: ${TWILIO_PHONENUMBER}

security.basic.enabled: false
management.security.enabled: false