spring:
  application:
    name: accounts-service
  rabbitmq:
    password: guest
    username: guest
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;MODE=PostgreSQL
  h2.console.enabled: true
  cloud.stream:
    bindings.output.destination: accountNotifications
    default.contentType: application/json

security.basic.enabled: false
management.security.enabled: false

server:
  compression.enabled: true
  port: 8080